spring:
  datasource:
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: warn
    com.sher.simpleblog: info
  file:
    name: log/blog-pro.log

server:
  port: 8081
