spring:
  datasource:
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${images.uploadPath}
  mvc:
    static-path-pattern: /**
#    show-sql: true
images:
  uploadPath: /home/sher/upload/

logging:
  level:
    root: info
    com.sher.simpleblog: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080



